resolver: lts-14.19
packages:
- '.'
extra-deps:
- extensible-0.7
- membership-0
- github: matsubara0507/mix.hs
  commit: 4978a33dec736799b30c14e215f7fa0f29fa2884
  subdirs:
  - mix

docker:
  repo: matsubara0507/stack-build
  enable: false
