resolver: lts-19.5
packages:
- '.'
extra-deps:
- extensible-0.8.3
- incremental-0.3.1
- membership-0.0.1
- github: matsubara0507/mix.hs
  commit: 9bcd386526fe10a025a23e951c2de86b05129b17
  subdirs:
  - mix

docker:
  repo: ghcr.io/matsubara0507/stack-build:18.04
  enable: false
