name: Build

on:
  pull_request: null
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ghc: ["8.10.4"]
        cabal: ["3.0"]
        cache-version: ["v1"]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-${{ matrix.cache-version }}
        restore-keys: |
          ${{ runner.os }}-stack-
    - name: Cache .stack/pantry
      id: cache-pantry
      uses: actions/cache@v1
      with:
        path: ~/.stack-temp/pantry
        key: ${{ runner.os }}-pantry-${{ hashFiles('**/stack.yaml.lock') }}-${{ matrix.cache-version }}
        restore-keys: |
          ${{ runner.os }}-pantry-
    - name: Move .stack/pantry to temp
      uses: matsubara0507/actions/move-files@master
      with:
        source_dir: ~/.stack-temp/pantry
        source_files: |
          pantry
        target_dir: ~/.stack

    - uses: actions/setup-haskell@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: mstksg/setup-stack@v1

    - name: Install dependencies
      run: stack --system-ghc test --only-dependencies

    - name: Run test
      run: stack --system-ghc test

    - name: Build binary
      run: stack --system-ghc install --local-bin-path=./bin

    - name: Build Docker Image
      run: docker build -t octkeys . --build-arg local_bin_path=./bin

    - name: Push Docker Image
      if: github.ref == 'refs/heads/master'
      run: |
        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u matsubara0507 --password-stdin
        docker tag octkeys matsubara0507/octkeys
        docker push matsubara0507/octkeys:latest
        docker logout
    - name: Push Docker Image (tag)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u matsubara0507 --password-stdin
        docker tag octkeys matsubara0507/octkeys:${GITHUB_REF#refs/tags/}
        docker push matsubara0507/octkeys:${GITHUB_REF#refs/tags/}
        docker logout
    - name: Display .stack size
      run: |
        du -sh ~/.stack/*
        du -sh .stack-work/*
